apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-deployment
  labels:
    app: weather
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: orikix/devopscapstone:latest
        ports:
        - containerPort: 80
        envFrom:
          - secretRef: SERVICE_ID
          - secretRef: API_KEY